# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAssist
                                 A QGIS plugin
 GeoAssist est un plugin QGIS d'analyse géospatiale intégrée, combinant traitement vectoriel et imagerie satellitaire pour l'aide à la décision en aménagement du territoire.
Le plugin se compose de deux modules complémentaires :

GeoAssist Aménagement — analyse vectorielle multi-projets dédiée à l'évaluation de projets de dérogation forestière. Il permet de définir des zones d'étude, calculer les intersections avec les domaines fonciers, évaluer l'éligibilité selon un moteur de décision multi-critères et générer automatiquement des rapports PDF et Word.
GeoAssist Sentinel — module de télédétection pour le téléchargement, la préparation et l'analyse d'images Sentinel-1 et Sentinel-2. Il automatise la création de compositions multispectrales et le calcul d'indices thématiques (NDVI, NDWI, NDBI, RVI, etc.).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-08
        copyright            : (C) 2026 by El Qasemy Niamat, Dhikli Amina, Azzouzi Aya, EL Hessenoui Asmae
        email                : dhikliamina@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoAssist class from file GeoAssist.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Geo_Assist import GeoAssist
    return GeoAssist(iface)
