# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAssistDialog
                                 A QGIS plugin
 GeoAssist est un plugin QGIS d'analyse géospatiale intégrée, combinant traitement vectoriel et imagerie satellitaire pour l'aide à la décision en aménagement du territoire.
Le plugin se compose de deux modules complémentaires :

GeoAssist Aménagement — analyse vectorielle multi-projets dédiée à l'évaluation de projets de dérogation forestière. Il permet de définir des zones d'étude, calculer les intersections avec les domaines fonciers, évaluer l'éligibilité selon un moteur de décision multi-critères et générer automatiquement des rapports PDF et Word.
GeoAssist Sentinel — module de télédétection pour le téléchargement, la préparation et l'analyse d'images Sentinel-1 et Sentinel-2. Il automatise la création de compositions multispectrales et le calcul d'indices thématiques (NDVI, NDWI, NDBI, RVI, etc.).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-08
        git sha              : $Format:%H$
        copyright            : (C) 2026 by El Qasemy Niamat, Dhikli Amina, Azzouzi Aya, EL Hessenoui Asmae
        email                : dhikliamina@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt.QtWidgets import QDialog, QVBoxLayout, QTabWidget
from qgis.PyQt.QtCore import Qt


from .modules.derogation.vecteur import VecteurDialog
from .modules.sentinel.sentinel_dialog import SentinelVisionDialog


class GeoAssistDialog(QDialog):

    def __init__(self, iface, parent=None):
        super().__init__(
            parent,
            Qt.Window |
            Qt.WindowMinimizeButtonHint |
            Qt.WindowMaximizeButtonHint |
            Qt.WindowCloseButtonHint
        )
        self.iface = iface
        self.setWindowTitle("GeoAssist")
        self.resize(1150, 800)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        self.tabs = QTabWidget()

        
        self.tab_derogation = VecteurDialog(iface=self.iface, parent=self)
        
        
        self.tab_derogation.setWindowFlags(Qt.Widget)
        self.tabs.addTab(self.tab_derogation, "Dérogation ")

        
        self.tab_sentinel = SentinelVisionDialog(iface=self.iface, parent=self)
        self.tab_sentinel.setWindowFlags(Qt.Widget)
        self.tabs.addTab(self.tab_sentinel, "Télédétection ")

        layout.addWidget(self.tabs)