# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoAssist
                                 A QGIS plugin
 GeoAssist est un plugin QGIS d'analyse géospatiale intégrée, combinant traitement vectoriel et imagerie satellitaire pour l'aide à la décision en aménagement du territoire.
Le plugin se compose de deux modules complémentaires :

GeoAssist Aménagement — analyse vectorielle multi-projets dédiée à l'évaluation de projets de dérogation forestière. Il permet de définir des zones d'étude, calculer les intersections avec les domaines fonciers, évaluer l'éligibilité selon un moteur de décision multi-critères et générer automatiquement des rapports PDF et Word.
GeoAssist Sentinel — module de télédétection pour le téléchargement, la préparation et l'analyse d'images Sentinel-1 et Sentinel-2. Il automatise la création de compositions multispectrales et le calcul d'indices thématiques (NDVI, NDWI, NDBI, RVI, etc.).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-06-08
        git sha              : $Format:%H$
        copyright            : (C) 2026 by El Qasemy Niamat, Dhikli Amina, Azzouzi Aya, EL Hessenoui Asmae
        email                : dhikliamina@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction


from .resources import *

from .Geo_Assist_dialog import GeoAssistDialog
import os.path


class GeoAssist:
    

    def __init__(self, iface):
        
        
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoAssist_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

       
        self.actions = []
        self.menu = self.tr(u'&GeoAssist')

        
        self.first_start = None

    
    def tr(self, message):
        
        return QCoreApplication.translate('GeoAssist', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        

        icon_path = ':/plugins/Geo_Assist/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'GeoAssist'),
            callback=self.run,
            parent=self.iface.mainWindow())

        
        self.first_start = True


    def unload(self):
        
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GeoAssist'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        
              
        
        if self.first_start == True:
            self.first_start = False
            self.dlg = GeoAssistDialog(iface=self.iface)

        
        self.dlg.show()
        self.dlg.raise_()          
        self.dlg.activateWindow()
